services:
  valheim:
    image: lloesche/valheim-server:latest
    cap_add: ["SYS_NICE"]
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    env_file: .env.valheim
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VALHEIM_LOG_FILTER_CONTAINS_SteamID: "Got connection SteamID"
      ON_VALHEIM_LOG_FILTER_CONTAINS_SteamID: >-
        { read l; msg="$$l"; curl -sfSL -X POST
        -H "Content-Type: application/json"
        -H "x-api-key: $${API_KEY}"
        -d "{\"line\":\"$${msg//\"/\\\"}\"}"
        "$${API_URL}/events/log"; }

      VALHEIM_LOG_FILTER_CONTAINS_Handshake: "Got handshake from client"
      ON_VALHEIM_LOG_FILTER_CONTAINS_Handshake: >-
        { read l; msg="$$l"; curl -sfSL -X POST
        -H "Content-Type: application/json"
        -H "x-api-key: $${API_KEY}"
        -d "{\"line\":\"$${msg//\"/\\\"}\"}"
        "$${API_URL}/events/log"; }

      # ---- Player join (Spawned) ----
      VALHEIM_LOG_FILTER_CONTAINS_Spawned: "Got character ZDOID from"
      ON_VALHEIM_LOG_FILTER_CONTAINS_Spawned: >-
        { read l; msg="$$l"; curl -sfSL -X POST
        -H "Content-Type: application/json"
        -H "x-api-key: $${API_KEY}"
        -d "{\"line\":\"$${msg//\"/\\\"}\"}"
        "$${API_URL}/events/log"; }

      # ---- Player leave (Closing socket) ----
      VALHEIM_LOG_FILTER_CONTAINS_ClosingSocket: "Closing socket"
      ON_VALHEIM_LOG_FILTER_CONTAINS_ClosingSocket: >-
        { read l; msg="$$l"; curl -sfSL -X POST
        -H "Content-Type: application/json"
        -H "x-api-key: $${API_KEY}"
        -d "{\"line\":\"$${msg//\"/\\\"}\"}"
        "$${API_URL}/events/log"; }

      # ---- Fallback leave (RPC_Disconnect) ----
      VALHEIM_LOG_FILTER_CONTAINS_RPCDisconnect: "RPC_Disconnect"
      ON_VALHEIM_LOG_FILTER_CONTAINS_RPCDisconnect: >-
        { read l; msg="$$l"; curl -sfSL -X POST
        -H "Content-Type: application/json"
        -H "x-api-key: $${API_KEY}"
        -d "{\"line\":\"$${msg//\"/\\\"}\"}"
        "$${API_URL}/events/log"; }
